branchName: '${issue.number}-${issue.title,}'
branches:
    - label: enhancement
      prefix: feature/
      name: develop
    - label: hotfix
      prefix: hotfix/
      name: main
    - label: together
      prefix: feature/
      name: hotfix
    - label: feature_together
      prefix: feature/
      name: feature/
    - label: '*'
      prefix: feature/

autoCloseIssue: true
gitSafeReplacementChar: '-'
silent: false
