branchName: '${issue.number}'
branches:
    - label: enhancement
      prefix: feature/
      name: develop
    - label: hotfix
      prefix: hotfix/
      name: main
    - label: together
      prefix: feature/
      name: hotfix
    - label: '*'
      prefix: feature/

autoCloseIssue: true
