name: Android CI

on:
  push:
    branches:
    - release/*
    - hotfix/*
    
  pull_request:
    branches: 
    - release/*
    - hotfix/*
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./SnapsMobileKR
    steps:
    - name: Set Time Zone
      run: sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    
    - uses: actions/checkout@v2
    
    - run: echo "${{ secrets.SIGNING_KEY_ALIAS }}" | base64 --decode > ./SnapsMobileKR/app/snaps.keystore
    - run: echo "${{ secrets.DEBUG_KEY_ALIAS }}" | base64 --decode > ./SnapsMobileKR/app/debug.keystore
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Build With Gradle
      run: ./gradlew assembleProductStgRelease assembleProductRealRelease
      working-directory: SnapsMobileKR

    - name: Apk Artifact Upload
      uses: actions/upload-artifact@v2
      with:
        name: snapsApk
        path: SnapsMobileKR/app/build/outputs/apk
        retention-days: 7

    - name: Slack Notification Finish With Success
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_ICON_EMOJI: ":bell:"
        SLACK_TITLE: ":bell: 빌드 성공"
        SLACK_COLOR: "#00BFA5"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack Notification Finish With Fail
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_ICON_EMOJI: ":boom:"
        SLACK_TITLE: ":boom: 빌드 실패"
        SLACK_COLOR: "#FF5252"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        
        
    - name: Find productReal APK
      id: find-productReal-apk
      run: |
          path=$(find **/build/outputs/apk/productReal -name '*.apk' -type f | head -1)
          echo "::set-output name=path::$path"
      working-directory: SnapsMobileKR
    
    - name: Find productStg APK
      id: find-productStg-apk
      run: |
          path=$(find **/build/outputs/apk/productStg -name '*.apk' -type f | head -1)
          echo "::set-output name=path::$path"
      working-directory: SnapsMobileKR
